export enum EntryType {
  TARGET = 'TARGET',
  COMMAND = 'COMMAND',
  PARALLEL_FLAG = 'PARALLEL_FLAG',
  DEPENDENCY = 'DEPENDENCY',
  COMMENT = 'COMMENT',
  VARIABLE_NAME = 'VARIABLE_NAME',
  VARIABLE_EQUALS = 'VARIABLE_EQUALS',
  VARIABLE_IFNOT = 'VARIABLE_IFNOT',
  VARIABLE_VALUE = 'VARIABLE_VALUE',
}
